# Generated by Django 5.1.3 on 2024-11-27 09:51

from django.db import migrations


def create_roles(apps, schema_editor):
    Role = apps.get_model('tenant', 'Role')
    Role.objects.create(name="U")  # User
    Role.objects.create(name="A")  # Admin
    Role.objects.create(name="S")  # Superuser


class Migration(migrations.Migration):
    dependencies = [
        ('tenant', '0001_initial'),  # Replace with the actual initial migration file
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
