# Generated by Django 5.1.3 on 2024-11-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20241127_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('U', 'user'), ('A', 'admin'), ('S', 'superuser')], default='U', max_length=1, unique=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('first_name', 'organization'), name='user: first name and organization constraint'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('last_name', 'organization'), name='user: last name and organization constraint'),
        ),
    ]
